# Generated by Django 2.1.5 on 2019-05-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190421_1701'),
        ('shop', '0004_item_tags'),
    ]

    operations = [
    ]
